### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by digitella** [nagahitoyuki/imaginary-grid#2]
Is there a way to move the sidebar (with contact form) to the bottom of the Posts? ;)

Superfast theme!

**Comment by nagahitoyuki** [comment]
Thank you for your comment.

Don't you want to use the sidebar in its current position at all?

If you just want to use some widgets below the post, set them in "Page Sub" section from layout of Blogger dashboard.

It's very hard to move the sidebar below the post properly. Because there are various cases related to the display of the blog. 

I think about how to remake the template, but it will take a few days or weeks.

**Comment by digitella** [comment]
Yeah... themes are difficult to manage. 

-- "It's very hard to move the sidebar below the post properly" 

-- YES. unfortunately

-- "I think about how to remake the template, but it will take a few days or weeks."

- Great!

**Comment by nagahitoyuki** [comment]
l updated the template to not show the sidebar. 

![footer-of-imaginary](https://user-images.githubusercontent.com/57346235/141397191-7f25caa4-016e-48dd-9ff0-e8870209e0c3.jpeg)

If you set the widget you want to use in the section under the post without showing the sidebar, it will be the same as moving the sidebar under the post.

### How to not show the sidebar

![blogger-theme-designer-width](https://user-images.githubusercontent.com/57346235/141397226-21c57f2f-30de-48bd-be99-8dccca341b30.jpeg)

Blogger dashboard >> Theme >> CUSTOMIZE >> Advanced >> Width

Set the values of Sidebar width and Content margin to 0. Then the sidebar of your blog disappear on both desktop and mobile.

### How to use the widget under the post

![blogger-layout](https://user-images.githubusercontent.com/57346235/141397255-d37931c1-d05b-4fdb-97fa-34ff69a4123f.jpeg)

Blogger dashboard >> Layout >> Page Sub

Set the widget you want to use from "Add a Gadget" in Page Sub section.

There are unnecessary codes, so you can delete them from Edit HTML.

**CSS part (inside b:skin tag)**

```
/* Balancer */
.sidebar-invisible, .sidebar-visible, .dim-overlay (these classes and all codes for them)

/* Side bar */
（All sidebar codes for all devises）

/* Side bar */
（All sidebar codes for desktop）

/* Side bar */
（All sidebar codes for mobile）
```

**CSS part (inside b:template-skin tag)**

`body#layout .sidebar-invisible {visibility:visible}`

**JavaScript part (inside script tag at the bottom of HTML)**

```
if (hil) hil.setAttribute(&quot;rel&quot;, &quot;nofollow&quot;);
↓
<b:if cond='data:skin.vars.sidebar_width or data:skin.vars.content_margin'>
(All codes for sidebar)
</b:if>
↑
/* Expand button */
```

None of them are used without the sidebar.
