### ISSUE TITLE
Header going past the float bar and behind the posts

### ISSUE THREAD

**Issue by DealsBeam** [nagahitoyuki/imaginary-grid#3]
https:// techgolem .blogspot.com/

Not sure if it's intentional or not

**Comment by nagahitoyuki** [comment]
It's intentional.

You can also customize to stop it.

`.hfeed {background-color:$(body.background.color);display:grid;grid-template-columns:repeat(auto-fill, minmax(320px, 1fr));gap:var(--maincolumn-padding)}
`

Add background-color to "hfeed" class.
